const ORIGINS=["https://amonguyen.hcdecorhub.com","http://localhost","http://127.0.0.1"];
const cors=req=>{const o=req.headers.get("origin")||"";return {"access-control-allow-origin":ORIGINS.some(x=>o.startsWith(x))?o:ORIGINS[0],"vary":"Origin","access-control-allow-headers":"content-type,x-store-id,authorization","access-control-allow-methods":"GET,POST,PATCH,OPTIONS"}};
const json=(req,data,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json","cache-control":"no-store",...cors(req)}});
const clean=s=>String(s??"").trim(),id=p=>p+"_"+crypto.randomUUID().replaceAll("-","").slice(0,20),slug=s=>clean(s).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const input=async req=>{try{return await req.json()}catch{return {}}};
const ADMIN_HASH="fa288af5f4224dd36158c9176b89e1156500b62921fa65a5c59af057155eeb70";
async function isAdmin(req,env){const t=(req.headers.get("authorization")||"").replace(/^Bearer\s+/,"");if(!t)return false;if(env?.TEST_ADMIN_TOKEN&&t===env.TEST_ADMIN_TOKEN)return true;const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(t));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")===ADMIN_HASH}
async function resolveStore(req,env){const key=req.headers.get("x-store-id")||new URL(req.url).searchParams.get("store")||"store_amo";return await env.DB.prepare("SELECT * FROM stores WHERE active=1 AND (id=? OR code=? OR slug=?)").bind(key,key,key).first()}
async function needAdmin(req,env){return await isAdmin(req,env)}
async function productDetail(env,store,key){const p=await env.DB.prepare("SELECT * FROM products WHERE store_id=? AND (id=? OR slug=?) AND status='active'").bind(store.id,key,key).first();if(!p)return null;const variants=(await env.DB.prepare("SELECT v.*,COALESCE(SUM(l.on_hand-l.reserved),0) available FROM variants v LEFT JOIN inventory_levels l ON l.variant_id=v.id AND l.store_id=v.store_id WHERE v.store_id=? AND v.product_id=? AND v.status='active' GROUP BY v.id ORDER BY v.size,v.color,v.sku").bind(store.id,p.id).all()).results;const images=(await env.DB.prepare("SELECT id,url,alt,sort_order FROM product_images WHERE store_id=? AND product_id=? ORDER BY sort_order,id").bind(store.id,p.id).all()).results;return {...p,variants,images}}
export default {async fetch(req,env){
 const u=new URL(req.url),path=u.pathname;if(req.method==="OPTIONS")return new Response(null,{headers:cors(req)});
 try{const store=await resolveStore(req,env);if(!store&&path!=="/api/health")return json(req,{error:"store not found"},404);
  if(path==="/api/health")return json(req,{ok:true,app:"HC Shop Engine",version:3});
  if(path==="/api/store")return json(req,{id:store.id,code:store.code,name:store.name,slug:store.slug,domain:store.domain,currency:store.currency,locale:store.locale});
  if(path==="/api/stores"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT id,code,name,slug,domain,currency,locale,active FROM stores WHERE active=1 ORDER BY created_at").all()).results})}
  if(path==="/api/stores"&&req.method==="POST"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const d=await input(req),code=clean(d.code).toUpperCase(),name=clean(d.name),sid=d.id||("store_"+slug(code)),ss=clean(d.slug)||slug(code);if(!code||!name)throw Error("code and name required");await env.DB.batch([env.DB.prepare("INSERT INTO stores(id,code,name,slug,domain,currency,locale,order_prefix) VALUES(?,?,?,?,?,?,?,?)").bind(sid,code,name,ss,clean(d.domain),d.currency||"VND",d.locale||"vi-VN",d.order_prefix||code),env.DB.prepare("INSERT INTO inventory_locations(id,store_id,name,code) VALUES(?,?,?,?)").bind("loc_"+code.toLowerCase()+"_main",sid,"Kho chinh","MAIN")]);return json(req,{ok:true,id:sid,slug:ss},201)}
  if(path==="/api/v1/stores"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT id,code,name,slug,domain,currency,locale,active FROM stores WHERE active=1 ORDER BY created_at").all()).results})}
  if(path==="/api/v1/brands"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT id,name,slug FROM brands WHERE store_id=? ORDER BY name").bind(store.id).all()).results})}
  if(path==="/api/v1/categories"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT id,name,slug FROM categories WHERE store_id=? ORDER BY name").bind(store.id).all()).results})}
  if(path==="/api/v1/product-drafts"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT * FROM product_drafts WHERE store_id=? ORDER BY updated_at DESC LIMIT 100").bind(store.id).all()).results})}
  if(path==="/api/v1/product-drafts"&&req.method==="POST"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const d=await input(req),name=clean(d.name);if(!name)throw Error("name required");const did=id("pdraft");await env.DB.prepare("INSERT INTO product_drafts(id,store_id,name,slug,brand_id,category_id,description,sku,barcode,cost,selling_price,warehouse_id,location_id,on_hand,incoming,payload_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(did,store.id,name,clean(d.slug)||slug(name),clean(d.brand_id)||null,clean(d.category_id)||null,clean(d.description),clean(d.sku)||null,clean(d.barcode)||null,d.cost==null?null:Number(d.cost),d.selling_price==null?null:Number(d.selling_price),clean(d.warehouse_id)||null,clean(d.location_id)||null,Math.max(0,Number(d.on_hand||0)),Math.max(0,Number(d.incoming||0)),JSON.stringify(d)).run();return json(req,{ok:true,id:did,status:"draft"},201)}
  const pdstate=path.match(/^\/api\/v1\/product-drafts\/([^/]+)\/state$/);if(pdstate&&req.method==="POST"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const d=await input(req),to=clean(d.to);const row=await env.DB.prepare("SELECT id,status FROM product_drafts WHERE id=? AND store_id=?").bind(pdstate[1],store.id).first();if(!row)return json(req,{error:"not found"},404);const allowed={draft:["review"],review:["draft","rejected"],rejected:["draft"]};if(!(allowed[row.status]||[]).includes(to))return json(req,{ok:false,error:"transition_not_allowed",from:row.status,to},423);await env.DB.prepare("UPDATE product_drafts SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND store_id=?").bind(to,row.id,store.id).run();return json(req,{ok:true,id:row.id,from:row.status,to})}
  if(path==="/api/v1/products"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT p.*,(SELECT url FROM product_images i WHERE i.product_id=p.id AND i.store_id=p.store_id ORDER BY sort_order,id LIMIT 1) image FROM products p WHERE p.store_id=? AND p.status!='archived' ORDER BY p.updated_at DESC,p.created_at DESC").bind(store.id).all()).results})}
  if(path==="/api/v1/variants"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const pid=u.searchParams.get("product_id");return json(req,{items:(await env.DB.prepare("SELECT * FROM variants WHERE store_id=? AND (? IS NULL OR product_id=?) ORDER BY sku").bind(store.id,pid,pid).all()).results})}
  if(path==="/api/v1/locations"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT wl.*,w.code warehouse_code,w.name warehouse_name FROM warehouse_locations wl JOIN warehouses w ON w.id=wl.warehouse_id WHERE wl.store_id=? ORDER BY w.code,wl.parent_id,wl.code").bind(store.id).all()).results})}
  if(path==="/api/v1/stock-movements"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT m.*,v.sku,p.name product_name FROM inventory_movements m JOIN variants v ON v.id=m.variant_id JOIN products p ON p.id=v.product_id WHERE m.store_id=? ORDER BY m.created_at DESC LIMIT 300").bind(store.id).all()).results})}
  if(path==="/api/v1/orders"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT * FROM orders WHERE store_id=? ORDER BY created_at DESC LIMIT 300").bind(store.id).all()).results})}
  if(path==="/api/v1/channels"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT id,code,name,type,active,config_json,created_at,updated_at FROM channels WHERE store_id=? ORDER BY code").bind(store.id).all()).results})}
  if(path==="/api/v1/listings"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const ch=u.searchParams.get("channel_id");return json(req,{items:(await env.DB.prepare("SELECT l.*,c.code channel_code,c.name channel_name,p.name product_name FROM listings l JOIN channels c ON c.id=l.channel_id JOIN products p ON p.id=l.product_id WHERE l.store_id=? AND (? IS NULL OR l.channel_id=?) ORDER BY l.updated_at DESC").bind(store.id,ch,ch).all()).results})}
  if(path==="/api/v1/warehouses"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const items=(await env.DB.prepare("SELECT * FROM warehouses WHERE store_id=? ORDER BY code").bind(store.id).all()).results;const locations=(await env.DB.prepare("SELECT * FROM warehouse_locations WHERE store_id=? ORDER BY warehouse_id,parent_id,code").bind(store.id).all()).results;return json(req,{items,locations})}
  if(path==="/api/v1/reservations"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT r.*,v.sku FROM reservations r JOIN variants v ON v.id=r.variant_id WHERE r.store_id=? ORDER BY r.created_at DESC LIMIT 300").bind(store.id).all()).results})}
  if(path==="/api/v1/import-jobs"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT id,kind,source_type,filename,status,summary_json,error_json,created_at,updated_at FROM import_jobs WHERE store_id=? ORDER BY created_at DESC LIMIT 100").bind(store.id).all()).results})}
  if(path==="/api/v1/import-jobs"&&req.method==="POST"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const d=await input(req),kind=clean(d.kind),source=clean(d.source_type)||"manual";if(!["products","inventory","price","customers","orders"].includes(kind))throw Error("invalid import kind");const jid=id("imp");await env.DB.prepare("INSERT INTO import_jobs(id,store_id,kind,source_type,filename,status,mapping_json) VALUES(?,?,?,?,?,'draft',?)").bind(jid,store.id,kind,source,clean(d.filename),JSON.stringify(d.mapping||{})).run();return json(req,{ok:true,id:jid,status:"draft"},201)}
  const istage=path.match(/^\/api\/v1\/import-jobs\/([^/]+)\/stage$/);if(istage&&req.method==="POST"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const d=await input(req),rows=Array.isArray(d.rows)?d.rows:[];if(!rows.length||rows.length>1000)throw Error("rows required; max 1000");const job=await env.DB.prepare("SELECT id,status FROM import_jobs WHERE id=? AND store_id=?").bind(istage[1],store.id).first();if(!job||!["draft","mapped","validated","dry_run"].includes(job.status))throw Error("job not stageable");const b=[];for(let i=0;i<rows.length;i++)b.push(env.DB.prepare("INSERT INTO import_staging(id,store_id,job_id,row_no,raw_json,canonical_json,status,errors_json) VALUES(?,?,?,?,?,?,'pending','[]') ON CONFLICT(job_id,row_no) DO UPDATE SET raw_json=excluded.raw_json,canonical_json=excluded.canonical_json,status='pending',errors_json='[]'").bind(id("row"),store.id,job.id,i+1,JSON.stringify(rows[i]),JSON.stringify(rows[i])));b.push(env.DB.prepare("UPDATE import_jobs SET status='mapped',updated_at=CURRENT_TIMESTAMP WHERE id=? AND store_id=?").bind(job.id,store.id));await env.DB.batch(b);return json(req,{ok:true,id:job.id,status:"mapped",rows:rows.length})}
  const idry=path.match(/^\/api\/v1\/import-jobs\/([^/]+)\/dry-run$/);if(idry&&req.method==="POST"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const job=await env.DB.prepare("SELECT * FROM import_jobs WHERE id=? AND store_id=?").bind(idry[1],store.id).first();if(!job)throw Error("job not found");const rows=(await env.DB.prepare("SELECT id,row_no,canonical_json FROM import_staging WHERE job_id=? AND store_id=? ORDER BY row_no").bind(job.id,store.id).all()).results;if(!rows.length)throw Error("no staged rows");let valid=0,invalid=0;const b=[];for(const row of rows){let x={};try{x=JSON.parse(row.canonical_json||"{}")}catch{};const errs=[];if(job.kind==="products"&&!clean(x.name))errs.push("name required");if(job.kind==="inventory"&&(!clean(x.sku)||!Number.isInteger(Number(x.qty))))errs.push("sku and integer qty required");if(job.kind==="price"&&(!clean(x.sku)||!Number.isFinite(Number(x.price))))errs.push("sku and numeric price required");if(errs.length)invalid++;else valid++;b.push(env.DB.prepare("UPDATE import_staging SET status=?,errors_json=? WHERE id=?").bind(errs.length?"invalid":"valid",JSON.stringify(errs),row.id))}const summary={rows:rows.length,valid,invalid,committed:0};b.push(env.DB.prepare("UPDATE import_jobs SET status='dry_run',summary_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND store_id=?").bind(JSON.stringify(summary),job.id,store.id));await env.DB.batch(b);return json(req,{ok:invalid===0,id:job.id,status:"dry_run",summary})}
  const idetail=path.match(/^\/api\/v1\/import-jobs\/([^/]+)$/);if(idetail&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const job=await env.DB.prepare("SELECT id,kind,source_type,filename,status,mapping_json,summary_json,error_json,created_at,updated_at FROM import_jobs WHERE id=? AND store_id=?").bind(idetail[1],store.id).first();if(!job)return json(req,{error:"not found"},404);const rows=(await env.DB.prepare("SELECT id,row_no,canonical_json,status,errors_json FROM import_staging WHERE job_id=? AND store_id=? ORDER BY row_no LIMIT 1000").bind(job.id,store.id).all()).results;return json(req,{...job,rows})}
  const icommit=path.match(/^\/api\/v1\/import-jobs\/([^/]+)\/commit$/);if(icommit&&req.method==="POST")return json(req,{ok:false,error:"approval_required",policy:"production_write_locked",id:icommit[1]},423);
  if(path==="/api/v1/inventory"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT v.sku,p.name,l.location_id,l.on_hand,l.reserved,l.incoming,(l.on_hand-l.reserved) available,l.variant_id FROM inventory_levels l JOIN variants v ON v.id=l.variant_id JOIN products p ON p.id=v.product_id WHERE l.store_id=? ORDER BY p.name,v.sku,l.location_id").bind(store.id).all()).results})}
  if(path==="/api/catalog"){const items=(await env.DB.prepare("SELECT p.*,b.name brand,b.slug brand_slug,c.name category,c.slug category_slug, (SELECT url FROM product_images i WHERE i.product_id=p.id AND i.store_id=p.store_id ORDER BY sort_order,id LIMIT 1) image, COALESCE((SELECT SUM(l.on_hand-l.reserved) FROM variants v JOIN inventory_levels l ON l.variant_id=v.id WHERE v.product_id=p.id AND v.store_id=p.store_id),0) available FROM products p LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN categories c ON c.id=p.category_id WHERE p.store_id=? AND p.status='active' ORDER BY p.created_at DESC").bind(store.id).all()).results;return json(req,{store:{id:store.id,name:store.name,currency:store.currency},items})}
  const pub=path.match(/^\/api\/catalog\/([^/]+)$/);if(pub){const p=await productDetail(env,store,pub[1]);return p?json(req,p):json(req,{error:"product not found"},404)}
  if(path==="/api/products"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT p.*,(SELECT url FROM product_images i WHERE i.product_id=p.id ORDER BY sort_order LIMIT 1) image FROM products p WHERE p.store_id=? AND p.status!='archived' ORDER BY p.created_at DESC").bind(store.id).all()).results})}
  if(path==="/api/products"&&req.method==="POST"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const d=await input(req);if(!clean(d.name))throw Error("name required");const pid=id("prd"),s=clean(d.slug)||slug(d.name);await env.DB.prepare("INSERT INTO products(id,store_id,name,slug,description,status,price,sale_price) VALUES(?,?,?,?,?,?,?,?)").bind(pid,store.id,clean(d.name),s,clean(d.description),d.status||"draft",Number(d.price||0),d.sale_price==null?null:Number(d.sale_price)).run();return json(req,{ok:true,id:pid,slug:s},201)}
  const pm=path.match(/^\/api\/products\/([^/]+)$/);if(pm&&req.method==="PATCH"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const d=await input(req);await env.DB.prepare("UPDATE products SET name=COALESCE(?,name),description=COALESCE(?,description),status=COALESCE(?,status),price=COALESCE(?,price),sale_price=COALESCE(?,sale_price),updated_at=CURRENT_TIMESTAMP WHERE id=? AND store_id=?").bind(d.name??null,d.description??null,d.status??null,d.price??null,d.sale_price??null,pm[1],store.id).run();return json(req,{ok:true})}
  if(path==="/api/images"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const pid=u.searchParams.get("product_id");return json(req,{items:(await env.DB.prepare("SELECT * FROM product_images WHERE store_id=? AND (? IS NULL OR product_id=?) ORDER BY product_id,sort_order").bind(store.id,pid,pid).all()).results})}
  if(path==="/api/images"&&req.method==="POST"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const d=await input(req);if(!d.product_id||!/^https?:\/\//.test(clean(d.url))&&!clean(d.url).startsWith("/"))throw Error("product_id and image url required");const iid=id("img");await env.DB.prepare("INSERT INTO product_images(id,store_id,product_id,url,alt,sort_order) VALUES(?,?,?,?,?,?)").bind(iid,store.id,d.product_id,clean(d.url),clean(d.alt),Number(d.sort_order||0)).run();return json(req,{ok:true,id:iid},201)}
  if(path==="/api/variants"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const pid=u.searchParams.get("product_id");return json(req,{items:(await env.DB.prepare("SELECT * FROM variants WHERE store_id=? AND (? IS NULL OR product_id=?) ORDER BY sku").bind(store.id,pid,pid).all()).results})}
  if(path==="/api/variants"&&req.method==="POST"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const d=await input(req);if(!d.product_id||!clean(d.sku))throw Error("product_id and sku required");const vid=id("var"),requestedLoc=clean(d.location_id);let loc="loc_"+store.code.toLowerCase()+"_main";if(requestedLoc){const bridge=await env.DB.prepare("SELECT inventory_location_id FROM warehouse_locations WHERE id=? AND store_id=? AND active=1").bind(requestedLoc,store.id).first();loc=bridge?.inventory_location_id||requestedLoc}await env.DB.batch([env.DB.prepare("INSERT INTO variants(id,store_id,product_id,sku,size,color,price,sale_price,status,barcode,cost,attributes_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(vid,store.id,d.product_id,clean(d.sku),clean(d.size),clean(d.color),d.price==null?null:Number(d.price),d.sale_price==null?null:Number(d.sale_price),"active",clean(d.barcode)||null,d.cost==null?null:Number(d.cost),JSON.stringify(d.attributes||{})),env.DB.prepare("INSERT INTO inventory_levels(store_id,location_id,variant_id,on_hand,reserved,incoming) VALUES(?,?,?,?,0,?)").bind(store.id,loc,vid,Number(d.on_hand||0),Number(d.incoming||0))]);return json(req,{ok:true,id:vid},201)}
  if(path==="/api/inventory"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT v.sku,p.name,v.size,v.color,l.on_hand,l.reserved,(l.on_hand-l.reserved) available,l.variant_id FROM inventory_levels l JOIN variants v ON v.id=l.variant_id JOIN products p ON p.id=v.product_id WHERE l.store_id=? ORDER BY p.name,v.sku").bind(store.id).all()).results})}
  if(path==="/api/inventory/adjust"&&req.method==="POST"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const d=await input(req),qty=Number(d.qty||0),loc=d.location_id||("loc_"+store.code.toLowerCase()+"_main");if(!Number.isInteger(qty)||!qty)throw Error("integer qty required");const old=await env.DB.prepare("SELECT on_hand,reserved FROM inventory_levels WHERE store_id=? AND location_id=? AND variant_id=?").bind(store.id,loc,d.variant_id).first(),next=(old?.on_hand||0)+qty;if(next<0||next<(old?.reserved||0))throw Error("insufficient inventory");await env.DB.batch([env.DB.prepare("INSERT INTO inventory_levels(store_id,location_id,variant_id,on_hand,reserved) VALUES(?,?,?,?,0) ON CONFLICT(location_id,variant_id) DO UPDATE SET on_hand=excluded.on_hand,updated_at=CURRENT_TIMESTAMP").bind(store.id,loc,d.variant_id,next),env.DB.prepare("INSERT INTO inventory_movements(id,store_id,location_id,variant_id,type,qty,reference_type,note) VALUES(?,?,?,?,?,?,?,?)").bind(id("mov"),store.id,loc,d.variant_id,d.type||"adjust",qty,"manual",clean(d.note))]);return json(req,{ok:true,on_hand:next})}
  if(path==="/api/orders"&&req.method==="POST"){const d=await input(req),items=Array.isArray(d.items)?d.items:[],name=clean(d.customer?.name),phone=clean(d.customer?.phone),email=clean(d.customer?.email),address=clean(d.customer?.address);if(!items.length||!name||!phone||!address)throw Error("customer name, phone, address and items required");let cid=(await env.DB.prepare("SELECT id FROM customers WHERE store_id=? AND phone=? LIMIT 1").bind(store.id,phone).first())?.id||id("cus");await env.DB.prepare("INSERT INTO customers(id,store_id,name,phone,email,address) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,email=excluded.email,address=excluded.address").bind(cid,store.id,name,phone,email,address).run();const oid=id("ord"),no=(store.order_prefix||store.code||"ORD")+"-"+Date.now(),batch=[];let total=0;for(const x of items){const q=Number(x.qty);if(!Number.isInteger(q)||q<1||q>20)throw Error("invalid qty");const v=await env.DB.prepare("SELECT v.*,p.name,p.price product_price,p.sale_price product_sale FROM variants v JOIN products p ON p.id=v.product_id WHERE v.id=? AND v.store_id=? AND v.status='active' AND p.status='active'").bind(x.variant_id,store.id).first();if(!v)throw Error("variant not found");const l=await env.DB.prepare("SELECT on_hand,reserved FROM inventory_levels WHERE store_id=? AND variant_id=?").bind(store.id,v.id).first();if(!l||l.on_hand-l.reserved<q)throw Error("insufficient stock");const price=v.sale_price??v.price??v.product_sale??v.product_price??0;total+=q*price;batch.push(env.DB.prepare("INSERT INTO order_items(id,store_id,order_id,variant_id,sku,name,qty,unit_price,line_total) VALUES(?,?,?,?,?,?,?,?,?)").bind(id("itm"),store.id,oid,v.id,v.sku,v.name,q,price,q*price))}
   batch.unshift(env.DB.prepare("INSERT INTO orders(id,store_id,order_no,status,customer_id,customer_name,customer_phone,customer_email,shipping_address,payment_method,subtotal,shipping_fee,total,note) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(oid,store.id,no,"new",cid,name,phone,email,address,clean(d.payment_method)||"cod",total,0,total,clean(d.note)));batch.push(env.DB.prepare("INSERT INTO order_status_history(id,store_id,order_id,from_status,to_status,note) VALUES(?,?,?,?,?,?)").bind(id("hst"),store.id,oid,null,"new","checkout"));await env.DB.batch(batch);return json(req,{ok:true,id:oid,order_no:no,total},201)}
  if(path==="/api/orders"&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT * FROM orders WHERE store_id=? ORDER BY created_at DESC").bind(store.id).all()).results})}
  const od=path.match(/^\/api\/orders\/([^/]+)$/);if(od&&req.method==="GET"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const order=await env.DB.prepare("SELECT * FROM orders WHERE store_id=? AND id=?").bind(store.id,od[1]).first();if(!order)return json(req,{error:"not found"},404);const items=(await env.DB.prepare("SELECT * FROM order_items WHERE store_id=? AND order_id=?").bind(store.id,od[1]).all()).results;const history=(await env.DB.prepare("SELECT * FROM order_status_history WHERE store_id=? AND order_id=? ORDER BY created_at").bind(store.id,od[1]).all()).results;return json(req,{...order,items,history})}
  const sm=path.match(/^\/api\/orders\/([^/]+)\/status$/);if(sm&&req.method==="POST"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const d=await input(req),o=await env.DB.prepare("SELECT * FROM orders WHERE id=? AND store_id=?").bind(sm[1],store.id).first();if(!o)throw Error("order not found");const allow={new:["confirmed","cancelled"],confirmed:["packing","cancelled"],packing:["shipping","cancelled"],shipping:["completed","returned"],completed:["returned"],cancelled:[],returned:[]};if(!allow[o.status]?.includes(d.status))throw Error("invalid status transition");const its=(await env.DB.prepare("SELECT * FROM order_items WHERE order_id=? AND store_id=?").bind(o.id,store.id).all()).results,b=[];for(const x of its){const l=await env.DB.prepare("SELECT * FROM inventory_levels WHERE store_id=? AND variant_id=?").bind(store.id,x.variant_id).first();let type=null,q=0;if(d.status==="confirmed"){if(!l||l.on_hand-l.reserved<x.qty)throw Error("insufficient stock "+x.sku);b.push(env.DB.prepare("UPDATE inventory_levels SET reserved=reserved+? WHERE store_id=? AND variant_id=?").bind(x.qty,store.id,x.variant_id));type="reserve";q=-x.qty}if(d.status==="cancelled"&&o.status!=="new"){b.push(env.DB.prepare("UPDATE inventory_levels SET reserved=MAX(0,reserved-?) WHERE store_id=? AND variant_id=?").bind(x.qty,store.id,x.variant_id));type="release";q=x.qty}if(d.status==="completed"){b.push(env.DB.prepare("UPDATE inventory_levels SET on_hand=on_hand-?,reserved=MAX(0,reserved-?) WHERE store_id=? AND variant_id=?").bind(x.qty,x.qty,store.id,x.variant_id));type="sale";q=-x.qty}if(d.status==="returned"){b.push(env.DB.prepare("UPDATE inventory_levels SET on_hand=on_hand+? WHERE store_id=? AND variant_id=?").bind(x.qty,store.id,x.variant_id));type="return";q=x.qty}if(type)b.push(env.DB.prepare("INSERT INTO inventory_movements(id,store_id,location_id,variant_id,type,qty,reference_type,reference_id,note) VALUES(?,?,?,?,?,?,?,?,?)").bind(id("mov"),store.id,l?.location_id||("loc_"+store.code.toLowerCase()+"_main"),x.variant_id,type,q,"order",o.id,d.status))}
   b.push(env.DB.prepare("UPDATE orders SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND store_id=?").bind(d.status,o.id,store.id),env.DB.prepare("INSERT INTO order_status_history(id,store_id,order_id,from_status,to_status,note) VALUES(?,?,?,?,?,?)").bind(id("hst"),store.id,o.id,o.status,d.status,clean(d.note)));await env.DB.batch(b);return json(req,{ok:true,status:d.status})}
  if(path==="/api/customers"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT * FROM customers WHERE store_id=? ORDER BY created_at DESC LIMIT 300").bind(store.id).all()).results})}
  if(path==="/api/promotions"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{items:(await env.DB.prepare("SELECT * FROM promotions WHERE store_id=? ORDER BY created_at DESC").bind(store.id).all()).results})}
  if(path==="/api/dashboard"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);const a=await env.DB.prepare("SELECT COALESCE(SUM(on_hand),0) total_stock,COALESCE(SUM(CASE WHEN on_hand-reserved<=2 THEN 1 ELSE 0 END),0) low_stock,COALESCE(SUM(CASE WHEN on_hand-reserved=0 THEN 1 ELSE 0 END),0) out_stock FROM inventory_levels WHERE store_id=?").bind(store.id).first(),b=await env.DB.prepare("SELECT COUNT(*) orders,COALESCE(SUM(CASE WHEN status='new' THEN 1 ELSE 0 END),0) new_orders,COALESCE(SUM(CASE WHEN status='completed' THEN total ELSE 0 END),0) revenue FROM orders WHERE store_id=?").bind(store.id).first();return json(req,{...a,...b})}
  if(path==="/api/reports"){if(!await needAdmin(req,env))return json(req,{error:"unauthorized"},401);return json(req,{best_sellers:(await env.DB.prepare("SELECT sku,name,SUM(qty) qty,SUM(line_total) revenue FROM order_items WHERE store_id=? GROUP BY sku,name ORDER BY qty DESC LIMIT 10").bind(store.id).all()).results,movements:(await env.DB.prepare("SELECT * FROM inventory_movements WHERE store_id=? ORDER BY created_at DESC LIMIT 100").bind(store.id).all()).results})}
  return json(req,{error:"not found"},404)
 }catch(e){return json(req,{ok:false,error:e.message},400)}
}};