const AMO_API="https://hc-shop-engine.huycuongonline.workers.dev",AMO_STORE="store_amo";let amoItems=[],amoFilter="all";
const amoMoney=n=>new Intl.NumberFormat("vi-VN").format(Number(n||0))+" đ";
const AMO_FALLBACK=[
{id:"ref-gucci-01",slug:"ref-gucci-loafer-05",name:"Men's Loafers 05",brand:"Gucci",brand_slug:"gucci",category:"Loafers",category_slug:"loafers",price:26000000,sale_price:16000000,image:"assets/reference/gucci-loafer-05.jpg",available:0,reference:true},
{id:"ref-gucci-02",slug:"ref-gucci-horsebit",name:"Horsebit Loafer Black",brand:"Gucci",brand_slug:"gucci",category:"Loafers",category_slug:"loafers",price:17000000,sale_price:14500000,image:"assets/reference/gucci-horsebit.jpg",available:0,reference:true},
{id:"ref-gucci-03",slug:"ref-gucci-geometric",name:"Geometric G Loafer",brand:"Gucci",brand_slug:"gucci",category:"Loafers",category_slug:"loafers",price:17500000,sale_price:14500000,image:"assets/reference/gucci-geometric.jpg",available:0,reference:true},
{id:"ref-gucci-04",slug:"ref-gucci-ace",name:"Ace Sneaker Interlocking G",brand:"Gucci",brand_slug:"gucci",category:"Sneakers",category_slug:"sneakers",price:12670000,sale_price:11000000,image:"assets/reference/gucci-ace.jpg",available:0,reference:true}
];
function amoRender(){const q=(amoSearch.value||"").trim().toLowerCase(),sort=amoSort.value;let a=amoItems.filter(p=>{const f=amoFilter==="all"||(amoFilter==="sale"&&p.sale_price)||(amoFilter==="new"&&!p.reference)||p.category_slug===amoFilter||p.brand_slug===amoFilter;return f&&(p.name+" "+(p.brand||"")+" "+(p.category||"")).toLowerCase().includes(q)});if(sort==="price-asc")a.sort((x,y)=>(x.sale_price??x.price)-(y.sale_price??y.price));if(sort==="price-desc")a.sort((x,y)=>(y.sale_price??y.price)-(x.sale_price??x.price));amoEmptyState.style.display=a.length?"none":"block";amoProductGrid.innerHTML=a.map(p=>'<a class="amo-product-card" href="'+(p.reference?"#":'product.html?p='+encodeURIComponent(p.slug))+'""><div class="amo-product-img"><img src="'+(p.image||"assets/images/demo/shoe-demo-1.jpg")+'" alt="'+p.name+'" loading="lazy" style="width:100%;height:100%;object-fit:cover"></div><div class="amo-product-info"><div style="font-size:.72rem;letter-spacing:.12em;color:#777">'+(p.brand||"AMO NGUYEN")+' · '+(p.category||"FOOTWEAR")+'</div><h2 class="amo-product-name">'+p.name+'</h2><div><b>'+amoMoney(p.sale_price??p.price)+'</b>'+(p.sale_price?'<del style="color:#999;margin-left:8px">'+amoMoney(p.price)+'</del>':'')+'</div><p class="amo-product-status">'+(p.reference?"Dữ liệu tham khảo · chưa mở bán":p.available>0?"Còn "+p.available+" sản phẩm":"Tạm hết hàng")+'</p></div></a>').join("")}
document.querySelectorAll(".amo-filter-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".amo-filter-btn").forEach(x=>{x.classList.toggle("is-active",x===b);x.setAttribute("aria-selected",x===b)});amoFilter=b.dataset.filter;amoRender()});amoSearch.oninput=amoRender;amoSort.onchange=amoRender;
fetch(AMO_API+"/api/catalog",{headers:{"x-store-id":AMO_STORE}}).then(r=>r.json()).then(d=>{amoItems=(d.items||[]).length?d.items:AMO_FALLBACK;amoRender()}).catch(()=>{amoItems=AMO_FALLBACK;amoRender()});